spring:
  main:
    banner-mode: off

http:
  keepAlive: false

# disable dns caching
networkaddress:
  cache:
    ttl: 0
    negative:
      ttl: 0

contest:
  ignoreinvalidconfig: true
  testprocessor:
    threads: 10
    shutdowntimeout: 60       #sec
  testenginehttp:
    readtimeout: 1000         #msec
    connecttimeout: 1000      #msec
  testresultwriterfile:
    logfile: contest.logg
    ignoreWriteErrors: false
  testresultwriteroutput:
    ignoreWriteErrors: false
  testresultsloader:
    ignoreErrors: true
    datafile: contest.logg
  testresultprocessor:
    latency:
      threshold: 10